[package]
name = "ophelia-quickcheck"
version = "0.1.0"
authors = ["zero.qn <zero.qn@outlook.com>"]
edition = "2018"
license = "MIT"
description = "ophelia quickcheck"

[dependencies]
ophelia-hasher = { path = "../ophelia-hasher", version = "0.1" }
quickcheck = "0.9"
